#!/usr/bin/env python3
"""Generate LaTeX CV versions from cv.yaml.

YAML is the source of truth. Each key under `profiles` becomes cv_<id>.tex.
Layout macros stay in structure.tex; this script only emits content.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required. From cv_source/ run: pip install -r requirements.txt")

ROOT = Path(__file__).resolve().parent
YAML_PATH = ROOT / "cv.yaml"

PREAMBLE = r"""%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% GENERATED FILE — do not edit.
% Source of truth: cv.yaml
% Regenerated by: python3 render_cv.py
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\documentclass[11pt,a4paper]{article}

\usepackage {enumitem}
\usepackage{changepage}
\usepackage{mdframed}

\usepackage[english]{babel}
\usepackage[style=numeric,sorting=ydnt]{biblatex}
\addbibresource{publications.bib}

\include{structure}

\hyphenation{Some-long-word}

\begin{document}
"""


def load_cv(path: Path = YAML_PATH) -> dict[str, Any]:
    with path.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not data or "profiles" not in data:
        raise SystemExit(f"No profiles found in {path}")
    return data


def visible(item: dict[str, Any] | None, tags: set[str]) -> bool:
    if not item:
        return False
    item_tags = item.get("tags")
    if not item_tags:
        return True
    return bool(set(item_tags) & tags)


def profile_tags(profile: dict[str, Any]) -> set[str]:
    return set(profile.get("tags") or [])


def root_title(name: str) -> str:
    return rf"\roottitle{{\lighter{{\textscale{{1.2}}{{{name}}}}}}}"


def hrule(before: str, after: str) -> str:
    return rf"\spacedhrule{{{before}}}{{{after}}}"


def date_box(dates: str, textsc: bool = True) -> str:
    inner = rf"\textsc{{{dates}}}" if textsc else dates
    return rf"{{\hfill [{inner}]}}"


def company_header(emp: dict[str, Any]) -> str:
    dates_sc = emp.get("dates_textsc", True)
    dates = date_box(emp["dates"], dates_sc)
    lead = r"\noindent" + "\n" if emp.get("leading_noindent") else ""
    return (
        f"{lead}{{\\textscale{{1.4}}{{\\textbf{{{emp['company']}}}}}}} \\\\\n"
        f"{{\\textsc{{{emp['location']}}}}}\n"
        f"{dates}"
    )


def project_heading(project: dict[str, Any]) -> str:
    name = project["name"]
    colon = project.get("colon", "inside")
    if colon == "inside":
        heading = rf"\textbf{{{name}:}}"
    elif colon == "inside_space":
        heading = rf"\textbf{{{name}: }}"
    elif colon == "outside":
        heading = rf"\textbf{{{name}}}:"
    elif colon == "none":
        heading = rf"\textbf{{{name}}}"
    else:
        raise ValueError(f"Unknown colon style: {colon}")
    indent = r"\indent " if project.get("indent") else ""
    return f"{indent}{heading}"


def render_projects(projects: list[dict[str, Any]]) -> str:
    blocks = []
    for project in projects:
        heading = project_heading(project)
        text = project["text"].rstrip()
        blocks.append(f"{heading} {text}")
    return "\n\n".join(blocks)


def href(url: str, label: str) -> str:
    return rf"\href{{{url.replace('&', r'\&')}}}{{{label}}}"


def role_title_line(role: dict[str, Any], inline_dates: bool = False) -> str:
    title = rf"\noindent {{\textscale{{1.2}} {{\textbf{{{role['title']}}}}}}}"
    if "dates" not in role:
        return title + r" \\"
    dates_sc = role.get("dates_textsc", True)
    dates = date_box(role["dates"], dates_sc)
    if inline_dates:
        return f"{title} {dates} \\\\"
    return f"{title}\n{dates}\\\\"


def render_role(role: dict[str, Any], detail: str) -> str:
    parts: list[str] = []
    brief = detail == "brief"

    if role.get("bullets"):
        parts.append(role_title_line(role, inline_dates=brief))
        if brief:
            parts.append(role["brief"].rstrip())
        else:
            bullets = " \\\\\n".join(rf"$\bullet$ {b.rstrip()}" for b in role["bullets"])
            parts.append(bullets)
    else:
        parts.append(role_title_line(role, inline_dates=False))
        if role.get("intro"):
            parts.append(role["intro"].rstrip())
        if role.get("projects"):
            if brief:
                if role.get("brief"):
                    parts.append("")
                    parts.append(role["brief"].rstrip())
            else:
                parts.append("")
                parts.append(render_projects(role["projects"]))
        elif brief and role.get("brief"):
            parts.append(role["brief"].rstrip())

    return "\n".join(parts)


def render_experience(data: dict[str, Any], profile: dict[str, Any]) -> str:
    tags = profile_tags(profile)
    detail = profile.get("detail", "full")
    pagebreak_after = set(profile.get("pagebreak_after") or [])
    chunks: list[str] = [root_title("EXPERIENCE"), "", r"\vspace{.2cm}", ""]

    for emp in data["experience"]:
        emp_visible = visible(emp, tags)
        if emp_visible:
            roles = [role for role in emp.get("roles", []) if visible(role, tags)]
            chunks.append(company_header(emp))
            chunks.append("")
            chunks.append(r"\begin{adjustwidth}{3em}{0pt}")
            chunks.append(r"\begin{leftrule}")
            chunks.append("")
            role_blocks: list[str] = []
            for i, role in enumerate(roles):
                block = render_role(role, detail)
                vspace = None
                if i < len(roles) - 1 or role.get("vspace_after"):
                    key = "vspace_after_brief" if detail == "brief" and role.get("vspace_after_brief") else "vspace_after"
                    vspace = role.get(key)
                role_blocks.append(block)
                if vspace:
                    role_blocks.append(rf"\vspace{{{vspace}}}")
                    role_blocks.append("")
            chunks.append("\n\n".join(role_blocks).rstrip())
            chunks.append("")
            chunks.append(r"\end{leftrule}")
            chunks.append(r"\end{adjustwidth}")
            chunks.append("")

        if emp.get("id") in pagebreak_after:
            chunks.append(r"\newpage")
            chunks.append("")

        after = emp.get("always_after_vspace")
        if after and (emp_visible or True):
            # Original source emitted these vspaces even when the employer was hidden.
            chunks.append(rf"\vspace{{{after}}}")
            chunks.append("")

    chunks.append(hrule("-0.4em", "0.5em"))
    chunks.append("")
    return "\n".join(chunks)


def render_summary(data: dict[str, Any], profile: dict[str, Any]) -> str:
    tags = profile_tags(profile)
    key = profile["summary"]
    parts = [p for p in data["summaries"][key] if visible(p, tags)]
    body = "\n\n".join(p["text"].rstrip() for p in parts)
    extra = profile.get("extra_vspace_after_summary")
    lines = [
        root_title("SUMMARY"),
        "",
        r"\vspace{.2cm}",
        "",
        r"\noindent",
        "",
        body,
        "",
    ]
    if extra:
        lines.append(rf"\vspace{{{extra}}}")
        lines.append("")
    lines.append(hrule("0.3em", "0.5em"))
    lines.append("")
    return "\n".join(lines)


def render_header(person: dict[str, Any]) -> str:
    phones = ",".join(rf"\textsmaller{{{p}}}" for p in person["phones"])
    links = [href(link["url"], link["label"]) for link in person["links"]]
    contact = " \\bull \n".join(
        [
            f"{{{person['location']}}}",
            rf"\href{{mailto:{person['email']}}}{{{person['email']}}}",
            phones,
            " \\bull \n".join(links),
        ]
    )
    return "\n".join(
        [
            rf"\maintitle{{{person['name']}}}{{{person['subtitle']}}}",
            "",
            r"\noindent",
            contact,
            "",
            hrule("0.3em", "0.5em"),
            "",
        ]
    )


def itemize(items: list[str], itemsep: str = "-0.1cm", leftmargin: str = "1cm") -> str:
    body = "\n".join(f"\t\\item {item}" for item in items)
    return (
        f"\\begin{{itemize}}[leftmargin={leftmargin}, itemsep={itemsep}]\n"
        f"{body}\n"
        r"\end{itemize}"
    )


def render_research_expertise(data: dict[str, Any], profile: dict[str, Any]) -> str:
    section = data["research_expertise"]
    if not visible(section, profile_tags(profile)):
        return ""
    return "\n".join(
        [
            root_title("RESEARCH EXPERTISE"),
            "",
            itemize(section["items"]),
            "",
            hrule("-0.7em", "0.5em"),
            "",
        ]
    )


def render_research_supervision(data: dict[str, Any], profile: dict[str, Any]) -> str:
    section = data["research_supervision"]
    if not visible(section, profile_tags(profile)):
        return ""
    rendered = []
    for item in section["items"]:
        body = " \\\\\n\t\t  ".join(item["lines"])
        rendered.append(f"\t\\item \\textbf{{{item['heading']}}} \\\\\n\t\t  {body}")
    list_body = (
        "\\begin{itemize}[leftmargin=1cm, itemsep=-0.1cm]\n"
        + "\n".join(rendered)
        + "\n\\end{itemize}"
    )
    return "\n".join(
        [
            root_title("RESEARCH SUPERVISION \\& GUIDANCE"),
            "",
            list_body,
            "",
            hrule("-0.7em", "0.5em"),
            "",
        ]
    )


def render_teaching(data: dict[str, Any], profile: dict[str, Any]) -> str:
    section = data["teaching_expertise"]
    if not visible(section, profile_tags(profile)):
        return ""
    groups = section["groups"]
    return "\n".join(
        [
            root_title("TEACHING EXPERTISE"),
            "",
            rf"\textbf{{{groups[0]['heading']}}} \\",
            r"\vspace{-0.7cm}",
            itemize(groups[0]["items"], itemsep="-0.2cm"),
            "",
            r"\vspace{-0.3cm}",
            "",
            rf"\noindent \textbf{{{groups[1]['heading']}}} {groups[1]['text']} \\",
            "",
            r"\vspace{-0.3cm}",
            "",
            rf"\noindent \textbf{{{groups[2]['heading']}}} {groups[2]['text']} \\",
            "",
            hrule("-0.5em", "0.5em"),
            "",
        ]
    )


def render_technical(data: dict[str, Any], profile: dict[str, Any]) -> str:
    items = [
        rf"\textbf{{{row['heading']}}} {row['text']}"
        for row in data["technical_expertise"]["items"]
    ]
    parts: list[str] = []
    if "technical_expertise" in (profile.get("pagebreak_before") or []):
        parts.extend([r"\newpage", ""])
    parts.extend(
        [
            root_title("TECHNICAL EXPERTISE"),
            "",
            itemize(items),
            "",
            hrule("-0.2em", "0.5em"),
            "",
        ]
    )
    return "\n".join(parts)


def render_education(data: dict[str, Any], profile: dict[str, Any]) -> str:
    detail = profile.get("detail", "full")
    parts = [root_title("EDUCATION"), "", r"\vspace{.2cm}", ""]
    entries = data["education"]
    if detail == "brief":
        blocks = []
        for i, edu in enumerate(entries):
            prefix = "" if i == 0 else r"\noindent "
            degree = edu.get("degree_brief", edu["degree"])
            rest = edu["brief"].split(" -- ", 1)[1]
            blocks.append(
                f"{prefix}\\textscale{{1.2}} {{\\textbf{{{degree}}}}} -- {rest} \\\\"
            )
        parts.append("\n\\vspace{.2cm}\n".join(blocks))
    else:
        blocks = []
        for i, edu in enumerate(entries):
            prefix = "" if i == 0 else r"\noindent "
            head = (
                f"{prefix}\\textscale{{1.2}} {{\\textbf{{{edu['degree']}}}}} \\\\\n"
                f"{{\\textsc{{{edu['year']}, {edu['institution']}}}}}\n"
                f"{{\\hfill \\textsc{{{edu['location']}}}}} \\\\"
            )
            details = " \\\\\n".join(edu.get("details") or [])
            blocks.append(f"{head}\n{details}")
        parts.append("\n\n\\vspace{.4cm}\n\n".join(blocks))
    parts.extend(["", hrule("0.3em", "0.5em"), ""])
    return "\n".join(parts)


def render_certificates(data: dict[str, Any]) -> str:
    items = []
    for cert in data["certificates"]:
        items.append(
            "\t\\item {\\noindent \\textscale{1.13} {\\textbf{"
            + cert["title"]
            + "}} \\\\\n\t{"
            + cert["issuer"]
            + "}}"
        )
    return "\n".join(
        [
            root_title("CERTIFICATES"),
            "",
            r"\vspace{.2cm}",
            "",
            r"\begin{enumerate}",
            "\n".join(items),
            r"\end{enumerate}",
            "",
            hrule("-0.3em", "0.5em"),
            "",
        ]
    )


def render_publications(data: dict[str, Any], profile: dict[str, Any]) -> str:
    section = data["publications"]
    if not visible(section, profile_tags(profile)):
        return ""
    return "\n".join(
        [
            root_title("PUBLICATIONS"),
            r"\vspace{0.2cm}",
            "",
            r"\printbibliography[heading=none]",
            "",
            hrule("-0.5em", "0.5em"),
            "",
        ]
    )


def render_scholarships(data: dict[str, Any], profile: dict[str, Any]) -> str:
    section = data["scholarships"]
    if not visible(section, profile_tags(profile)):
        return ""
    items = "\n".join(f"\t\\item {item}" for item in section["items"])
    return "\n".join(
        [
            root_title("SCHOLARSHIPS"),
            "",
            r"\vspace{.2cm}",
            "",
            r"\begin{itemize}",
            items,
            r"\end{itemize}",
            "",
            hrule("-0.3em", "0.5em"),
            "",
        ]
    )


def render_journal_reviewer(data: dict[str, Any], profile: dict[str, Any]) -> str:
    section = data["journal_reviewer"]
    if not visible(section, profile_tags(profile)):
        return ""
    items = []
    for item in section["items"]:
        items.append(
            "\t\\item {\\textscale{1.13} {\\textbf{"
            + item["title"]
            + "}} \\\\\n\t\t\t\t{"
            + item["publisher"]
            + "}\n\t}"
        )
    return "\n".join(
        [
            root_title("JOURNAL REVIEWER"),
            "",
            r"\vspace{.2cm}",
            "",
            r"\begin{itemize}",
            "\n".join(items),
            r"\end{itemize}",
            "",
            hrule("0.2em", "0.5em"),
            "",
        ]
    )


def render_references(data: dict[str, Any]) -> str:
    items = []
    for ref in data["references"]:
        items.append(
            "\t\\item {\\noindent \\textscale{1.13} {\\textbf{"
            + ref["name"]
            + "}} \n"
            "                ("
            + href(ref["linkedin"], "LinkedIn")
            + ") \\\\\n"
            "\t\t\t\t{"
            + ref["title"]
            + "} \\\\\n"
            "\t\t\t\t{Mob: "
            + ref["phone"]
            + "} \\\\\n"
            "\t\t\t\t{Email: "
            + ref["email"]
            + "}}"
        )
    return "\n".join(
        [
            root_title("REFERENCES"),
            "",
            r"\vspace{.2cm}",
            "",
            r"\begin{enumerate}",
            "\n".join(items),
            r"\end{enumerate}",
            "",
        ]
    )


def render_profile(data: dict[str, Any], name: str) -> str:
    profile = data["profiles"][name]
    sections = [
        PREAMBLE.rstrip(),
        "",
        render_header(data["person"]),
        render_summary(data, profile),
        render_experience(data, profile),
        render_research_expertise(data, profile),
        render_research_supervision(data, profile),
        render_teaching(data, profile),
        render_technical(data, profile),
        render_education(data, profile),
        render_certificates(data),
        render_publications(data, profile),
        render_scholarships(data, profile),
        render_journal_reviewer(data, profile),
        render_references(data),
        r"\end{document}",
        "",
    ]
    return "\n".join(section for section in sections if section is not None)


def write_all(data: dict[str, Any], out_dir: Path) -> list[Path]:
    written = []
    for name in data["profiles"]:
        path = out_dir / f"cv_{name}.tex"
        path.write_text(render_profile(data, name), encoding="utf-8")
        written.append(path)
    return written


def self_test(data: dict[str, Any]) -> None:
    rendered = {name: render_profile(data, name) for name in data["profiles"]}
    detailed = rendered["detailed"]
    industry = rendered["industry"]
    brief = rendered["brief"]
    noresearch = rendered["noresearch"]

    def must(condition: bool, message: str) -> None:
        if not condition:
            raise AssertionError(message)

    must("RESEARCH EXPERTISE" in detailed, "detailed missing research expertise")
    must(r"\printbibliography" in detailed, "detailed missing publications")
    must("University of Johannesburg" in detailed, "detailed missing UJ")
    must("speech emotion recognition" in detailed, "detailed missing PhD paragraph")
    must("Medical Coding Co-pilot:" in detailed, "detailed missing full project")
    must(
        r"\textbf{Senior Data Scientist}}} \\" in detailed,
        "role titles should force a line break",
    )

    must("RESEARCH EXPERTISE" not in industry, "industry should hide research")
    must(r"\printbibliography" not in industry, "industry should hide publications")
    must("University of Johannesburg" in industry, "industry should still mention UJ in summary")
    must("Post Doctoral Research Fellow" not in industry, "industry should hide UJ role")
    must("STT, RAG" in industry, "industry missing tailored summary")
    must(r"\newpage" in industry, "industry missing page breaks")
    must("Medical Coding Co-pilot:" in industry, "industry should keep full project detail")

    must("Key projects:" in brief, "brief missing condensed projects")
    must("19+ years" in brief, "brief missing short summary")
    must("Applied ML" in brief, "brief missing condensed education")
    must("RESEARCH EXPERTISE" not in brief, "brief should hide research")
    must("Medical Coding Co-pilot:" not in brief or "Key projects: Medical Coding Co-pilot" in brief, "brief should condense projects")

    must("Medical Coding Co-pilot:" in noresearch, "noresearch should keep full projects")
    must("speech emotion recognition" not in noresearch, "noresearch should drop PhD summary paragraph")
    must("RESEARCH EXPERTISE" not in noresearch, "noresearch should hide research sections")
    must("SIEMENS" in noresearch, "noresearch should keep SIEMENS")
    must("DeliverHealth Solutions" in noresearch, "noresearch should keep industry roles")

    for name, tex in rendered.items():
        must(r"\begin{document}" in tex and r"\end{document}" in tex, f"{name} is not a complete document")
        must(tex.count("{") == tex.count("}"), f"{name} has unbalanced braces")

    print("self-test passed for profiles:", ", ".join(rendered))


def main() -> None:
    parser = argparse.ArgumentParser(description="Render CV LaTeX from cv.yaml")
    parser.add_argument("--profile", help="Render a single profile (default: all)")
    parser.add_argument("--list", action="store_true", help="Print profile ids")
    parser.add_argument("--list-tex", action="store_true", help="Print generated tex filenames")
    parser.add_argument("--self-test", action="store_true", help="Validate rendered versions")
    parser.add_argument("--stdout", action="store_true", help="Write a single profile to stdout")
    parser.add_argument("--dir", type=Path, default=ROOT, help="Output directory")
    args = parser.parse_args()

    data = load_cv()

    if args.list:
        print(" ".join(data["profiles"]))
        return
    if args.list_tex:
        for name in data["profiles"]:
            print(f"cv_{name}.tex")
        return
    if args.self_test:
        self_test(data)
        return
    if args.profile:
        if args.profile not in data["profiles"]:
            raise SystemExit(f"Unknown profile {args.profile}. Known: {', '.join(data['profiles'])}")
        tex = render_profile(data, args.profile)
        if args.stdout:
            sys.stdout.write(tex)
            return
        path = args.dir / f"cv_{args.profile}.tex"
        path.write_text(tex, encoding="utf-8")
        print(path)
        return

    written = write_all(data, args.dir)
    for path in written:
        print(path)


if __name__ == "__main__":
    main()
